services:
  mongodb:
    image: mongo:latest
    container_name: invoice_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server
    env_file:
      - ./server/.env
    container_name: invoice_backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongodb:27017/invoice_generator
      - OLLAMA_HOST=${OLLAMA_HOST}
      - EMAIL_USER=lucianbutuc16@gmail.com
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_HOST=imap.gmail.com
      - EMAIL_PORT=993
      - RESEND_API_KEY=${RESEND_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - CLIENT_URL=${CLIENT_URL}
      - STRIPE_PRICE_PRO=${STRIPE_PRICE_PRO}
      - STRIPE_PRICE_ENTERPRISE=${STRIPE_PRICE_ENTERPRISE}
    depends_on:
      - mongodb

  frontend:
    build: ./client
    container_name: invoice_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  mongo_data: