version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: invoice_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server
    container_name: invoice_backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongodb:27017/invoice_generator
      - OLLAMA_HOST=http://host.docker.internal:11434
      - EMAIL_USER=lucianbutuc16@gmail.com
      - EMAIL_PASSWORD=zmot ognk ikgp rzes
      - EMAIL_HOST=imap.gmail.com
      - EMAIL_PORT=993
      - RESEND_API_KEY=re_WgqJm6Tx_DsMRhme6bmGRaEwfSDtEvyVn
      - RESEND_FROM=invoiceGenAi <onboarding@resend.dev>
    depends_on:
      - mongodb


  frontend:
    build: ./client
    container_name: invoice_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend

volumes:
  mongo_data: