import fs from "fs";
import PDFDocument from "pdfkit";
import { Resend } from "resend";
import dotenv from "dotenv";
dotenv.config();

const resend = new Resend(process.env.RESEND_API_KEY);

const accent = [58 / 255, 110 / 255, 165 / 255];
const lightGray = "#dddddd";

// design pdf
const generateInvoicePDF = (invoice, client) => {
  const pdfPath = `./invoice_${invoice.invoice_number}.pdf`;
  const doc = new PDFDocument({ margin: 40 });
  const writeStream = fs.createWriteStream(pdfPath);
  doc.pipe(writeStream);

  const accent = "#3A6EA5";
  const gray = "#3C3C3C";
  const lightGray = "#E5E7EB";

  //HEADER (LOGO + TITLU + LINIE)
  try {
    doc.image("server/assets/logo.png", 40, 30, { width: 30 });
  } catch {
    console.warn("Missing logo, skipping image");
  }

  doc
    .font("Helvetica-Bold")
    .fontSize(22)
    .fillColor("black")
    .text("BillForge AI", 80, 32);
  doc
    .font("Helvetica")
    .fontSize(10)
    .fillColor("#666")
    .text("Smart Invoice Generator", 80, 50);

  doc.moveTo(40, 70).lineTo(555, 70).strokeColor(lightGray).stroke();

  // COMPANY & CLIENT INFO 
  let y = 90;
  doc.fontSize(13).fillColor(accent).font("Helvetica-Bold").text("From:", 40, y);
  doc.fontSize(11).fillColor(gray).font("Helvetica");
  y += 16;
  doc.text("invoiceGenAI Inc.", 40, y);
  doc.text("123 Innovation Blvd", 40, (y += 14));
  doc.text("Timișoara, Romania", 40, (y += 14));
  doc.text("support@invoicegen.ai", 40, (y += 14));

  let rightY = 90;
  const c = client || {};
  doc.font("Helvetica-Bold").fillColor(accent).text("Bill To:", 330, rightY);
  doc.font("Helvetica").fillColor(gray);
  rightY += 16;
  doc.text(c.name || "Unknown Client", 330, rightY);
  if (c.company && c.company !== c.name) doc.text(c.company, 330, (rightY += 14));
  if (c.email) doc.text(c.email, 330, (rightY += 14));
  if (c.phone) doc.text(c.phone, 330, (rightY += 14));
  if (c.address) doc.text(c.address, 330, (rightY += 14));

  // INVOICE INFO 
  const infoY = Math.max(y, rightY) + 25;
  doc.font("Helvetica-Bold").fillColor(accent).text("Invoice Details:", 40, infoY);
  doc.font("Helvetica").fillColor(gray);
  doc.text(`Invoice Number: ${invoice.invoice_number}`, 40, infoY + 15);
  doc.text(`Date: ${new Date(invoice.date).toLocaleDateString()}`, 40, infoY + 30);
  doc.text(
    `Due Date: ${
      invoice.due_date ? new Date(invoice.due_date).toLocaleDateString() : "-"
    }`,
    40,
    infoY + 45
  );
  doc.text(`Status: ${invoice.status}`, 40, infoY + 60);

  // TABLE HEADER 
  const tableY = infoY + 90;
  doc.rect(40, tableY, 520, 25).fill(accent);
  doc.fillColor("white").font("Helvetica-Bold").fontSize(12);
  doc.text("Description", 50, tableY + 7);
  doc.text("Quantity", 280, tableY + 7);
  doc.text("Unit Price", 380, tableY + 7);
  doc.text("Total", 480, tableY + 7);

  // TABLE ROWS
  let rowY = tableY + 25;
  doc.font("Helvetica").fontSize(11);

  invoice.items.forEach((item, i) => {
    const bg = i % 2 === 0 ? "#F5F7FA" : "#FFFFFF";
    doc.rect(40, rowY, 520, 20).fill(bg);
    doc.fillColor(gray);
    doc.text(item.description, 50, rowY + 5, { width: 200 });
    doc.text(String(item.quantity), 290, rowY + 5);
    doc.text(`$${item.unit_price.toFixed(2)}`, 380, rowY + 5);
    doc.text(`$${item.total.toFixed(2)}`, 480, rowY + 5);
    rowY += 20;
  });

  // TOTALS
  rowY += 15;
  doc.font("Helvetica-Bold").fillColor(accent).text("Summary", 390, rowY);
  doc.font("Helvetica").fillColor(gray).fontSize(11);
  rowY += 15;
  doc.text("Subtotal:", 390, rowY);
  doc.text(`$${invoice.subtotal.toFixed(2)}`, 480, rowY, { align: "right" });
  rowY += 15;
  doc.text("Tax Rate:", 390, rowY);
  doc.text(`${invoice.tax_rate}%`, 480, rowY, { align: "right" });
  rowY += 15;
  doc.text("Discount:", 390, rowY);
  doc.text(`${invoice.discount_rate}%`, 480, rowY, { align: "right" });
  rowY += 20;
  doc.font("Helvetica-Bold").fillColor(accent).fontSize(13);
  doc.text("Total:", 390, rowY);
  doc.text(`$${invoice.total.toFixed(2)}`, 480, rowY, { align: "right" });

  // NOTES
  if (invoice.notes) {
    rowY += 40;
    doc.font("Helvetica-Bold").fillColor(accent).text("Notes:", 40, rowY);
    doc.font("Helvetica").fillColor(gray).fontSize(11);
    doc.text(invoice.notes, 40, rowY + 15, { width: 500 });
  }

  // SIGNATURES
  const signY = rowY + 70;
  doc.moveTo(80, signY).lineTo(220, signY).strokeColor(lightGray).stroke();
  doc.moveTo(330, signY).lineTo(470, signY).strokeColor(lightGray).stroke();
  doc.fontSize(10).fillColor("#666");
  doc.text("Client Signature", 110, signY + 5);
  doc.text("Authorized Signature", 355, signY + 5);

  // FOOTER 
  doc.fontSize(9).fillColor("#999");
  doc.text("Generated by invoiceGenAI • www.invoicegen.ai", 40, 780, {
    align: "center",
  });

  doc.end();

  return new Promise((resolve, reject) => {
    writeStream.on("finish", () => resolve(pdfPath));
    writeStream.on("error", reject);
  });
};



export const sendInvoiceEmail = async (invoice, client) => {
  // Verificăm dacă structura de client conține o adresă de e-mail validă
  if (!client?.email) {
    console.warn("⚠️ [EmailService] Client has no email, skipping email send.");
    return;
  }

  try {
    console.log(`[EmailService] Se generează PDF-ul pentru factura ${invoice.invoice_number || 'draft'}...`);
    const pdfPath = await generateInvoicePDF(invoice, client);

    // Citirea fișierului PDF generat temporar din memoria Docker și conversia în Base64
    const pdfData = fs.readFileSync(pdfPath);
    const pdfBase64 = pdfData.toString("base64");

    console.log(`[EmailService] Se expediază e-mailul prin Resend către adresa de test...`);
    
    const response = await resend.emails.send({
      from: "onboarding@resend.dev",
      // FORȚAT: Conturile gratuite Resend în mod Sandbox acceptă doar adresa ta confirmată la înregistrare
      to: "butuclucian04@gmail.com", 
      subject: `Factură nouă emisă de invoiceGenAI: ${invoice.series || 'INV'}-${invoice.invoice_number}`,
      html: `
        <div style="font-family: Arial, sans-serif; padding: 20px; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #eee; border-radius: 12px;">
          <h2 style="color: #4F46E5; text-align: center;">Hello ${client.name || "Client"},</h2>
          <p style="text-align: center; font-size: 15px;">You’ve received a new invoice from <b>invoiceGenAI</b>.</p>
          
          <div style="margin: 20px auto; max-width: 400px; background: #f9f9f9; padding: 20px; border-radius: 10px; border-left: 4px solid #4F46E5;">
            <p style="margin: 5px 0;"><b>Invoice Number:</b> ${invoice.series || 'INV'}-${invoice.invoice_number}</p>
            <p style="margin: 5px 0;"><b>Total Amount:</b> ${invoice.total?.toFixed(2)} ${invoice.currency || 'RON'}</p>
            <p style="margin: 5px 0;"><b>Due Date:</b> ${invoice.due_date ? new Date(invoice.due_date).toLocaleDateString('ro-RO') : "—"}</p>
          </div>
          
          <p style="text-align: center; font-size: 14px; color: #666;">The official PDF document is attached to this email.</p>
          <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;" />
          <p style="text-align: center; color: #999; font-size: 12px;">Thank you for your business!<br><b>invoiceGenAI Team</b></p>
        </div>
      `,
      attachments: [
        {
          filename: `Invoice_${invoice.series || 'INV'}-${invoice.invoice_number}.pdf`,
          content: pdfBase64,
        },
      ],
    });

    // Gestionarea erorilor returnate direct în interiorul obiectului response de către Resend
    if (response.error) {
      console.error("❌ [EmailService] Resend validation error:", response.error);
      throw new Error(response.error.message || "Resend failed to deliver email");
    } else {
      console.log("\x1b[32m✉️ [EmailService] Invoice email sent successfully via Resend to butuclucian04@gmail.com!\x1b[0m");
    }

    // Ștergerea fișierului PDF temporar pentru a păstra containerul Docker curat
    fs.unlink(pdfPath, (err) => {
      if (err) console.warn("⚠️ [EmailService] Could not delete temp PDF:", err.message);
      else console.log("🧹 [EmailService] Temp PDF deleted successfully from workspace.");
    });

    return response;

  } catch (error) {
    console.error("❌ [EmailService] Fatal error sending invoice email:", error.message || error);
    // Transmitem eroarea mai departe pentru a bloca execuția greșită a controllerului HTTP
    throw error; 
  }
};